### ISSUE TITLE
Add default subchart versions to daskhub readme / Are subchart versions configurable?

### ISSUE THREAD

**Issue by scottyhq** [dask/helm-chart#113]
daskhub wraps jupyterhub and dask-gateway helm chart, which are versioned:
https://github.com/dask/helm-chart/blob/c1b7f9d64c4ae70dcb99b1f0334261f5ee782c29/daskhub/Chart.yaml#L7-L15

Is it possible to do a `helm install` that overrides the default version (for example jupyterhub 0.9.0)? 

Automated version bumps were previously discussed over in https://github.com/pangeo-data/helm-chart/issues/124 but never fully implemented

**Comment by jacobtomlinson** [comment]
According to helm/helm#205 it seems this is still an open feature request in helm. So I don't think this is possible.

We have #71 open to discuss automating version bumps but it has not yet been implemented.

**Comment by consideRatio** [comment]
## Action plan
- [ ] Update [Helm chart repo's index.md](https://github.com/dask/helm-chart/blob/gh-pages/index.md) to reference the jupyterhub helm chart and dask gateway helm chart version.
  - [ ] This requires information to be available in the [Helm chart repo's index.yaml file](https://github.com/dask/helm-chart/blob/gh-pages/index.md),
  - [ ] This requires an `apiVersion: 2` in the Helm chart, which let the requirements.yaml file become embedded into the Chart.yaml file, allowing that information to be available in `index.yaml` for extraction to be presented in `index.md`. Helm 2 reach end of life in a week, and the old versions of these helm charts will remain valid. I think a bump is fine as old chart versions are still valid anyhow.

## Background understanding
- A Helm chart repository where packaged Helm charts (bundle of templates + default values) are published, is simply a `index.yaml` file of a certain format that provides links to .tar files with the packaged Helm charts that contains whats in the the folder where Chart.yaml is.
- This git hub repo's gh-pages branch is the actual Helm chart repository where published charts have been packaged.
- This git hub repo's gh-pages branch also renders into a website with GitHub Pages system using Jekyll etc. For documentation on how to locally develop these things, see my documentation in https://github.com/jupyterhub/helm-chart#local-development-of-github-page

**Comment by consideRatio** [comment]
I think this is resolved going onwards. in #305 we make daskhub's appVersion field in its Chart.yaml file represent a combination of the jupyterhub's version and dask-gateway's version.

Actually, looking at https://helm.dask.org, it seems that we already expose notes about the version of JupyterHub and Dask-gateway very clearly. Going onwards, the App field will change to reflect the `appVersion` in daskhub/Chart.yaml
![image](https://user-images.githubusercontent.com/3837114/183071504-e432f636-e560-4889-bedf-7283a28b99ea.png)

**Comment by consideRatio** [comment]
Oh, note that subchart versions are not configurable, and we can't make them configurable. This is a foundational limitation of helm charts.
